### ISSUE TITLE
AKS Deploy helper - AKS Private Cluster

### ISSUE THREAD

**Issue by abymsft** [Azure/AKS-Construction#216] opened 2022-02-15 12:18 UTC
**Describe the bug**
Getting a deployment error when I use the deployment helper to deploy a private AKS cluster (without Sample APPs). 

**To Reproduce**
1. Go to 'https://azure.github.io/AKS-Construction/...'
2. Click on '"**I want a managed environment**"'
3. Scroll down and select '**Private cluster with isolating networking controls**'
4. Click on '"**Networking Details**"
5. Select  "**Deploy Azure firewall for your cluster egress (Custom VNet Only)**"
6. Select '"Use Azure Bastion to facilitate RDP/SSH public internet inbound access into your virtual network"'
7. Select **"Uses a private IP address from your VNet to access your dependent Azure service, such as Azure KeyVault, Azure Container Registry etc"**
8. Select "CNI" network plugin
9. Select "Custom Networkin"
10. All other options/selections remain default (no changes)

**Expected behavior**
A successful deployment of a private AKS cluster through Azure CLI

**Screenshots**
![image](https://user-images.githubusercontent.com/50873759/154058904-ea0eb320-fa95-40f5-a826-e2a2b4e6843f.png)
![image](https://user-images.githubusercontent.com/50873759/154059470-e0dd8649-ec7c-4c80-865b-2b358d42cda2.png)

**Additional context**
P.S. Everything works fine when I use the 0.4.5 template.
![image](https://user-images.githubusercontent.com/50873759/154060728-5248f4c2-7410-4030-ab0b-5311322fa6af.png)

**Comment by Gordonby** [comment] 2022-02-15 12:25
Duplicate of #210 
PR is raised awaiting approval #211

**Closed** 2022-02-15 15:01 UTC
Labels: bug
