### ISSUE TITLE
Catch certain incompatible configurations in the UI

### ISSUE THREAD

**Issue by liamfoneill** [Azure/AKS-Construction#420] opened 2022-10-02 10:51 UTC
**Describe the solution you'd like**
I would like to have the deploy helper flag if certain incompatible configuration choices are made - an example would be choosing B2s nodes sizes and also choosing ephemeral OS disks. 

**Describe alternatives you've considered**
The alternative is have ARM catch this at deploy time.

**Additional context**
![image](https://user-images.githubusercontent.com/1243172/193450350-fd7cc930-8926-48e3-bef3-d4f5c9f95443.png)

**Comment by Gordonby** [comment] 2022-10-04 15:53
I think this is a duplicate of #383 which was fixed by #412
We just need to do a release to get this out there.

**Comment by Gordonby** [comment] 2022-10-07 14:49
0.9.0 and the helper release should fix this

**Closed by Gordonby** 2022-10-07 14:49 UTC
Labels: duplicate
